FROM golang:1.17-buster as builder
WORKDIR /fn

COPY go.* ./
RUN go mod download

COPY . ./

RUN make build-bedrock-version

FROM debian:buster-slim

RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /fn/bin/bedrock-version /fn/bedrock-version

CMD ["/fn/bedrock-version"]