FROM golang:1.16-buster as builder
WORKDIR /fn

COPY go.* ./
RUN go mod download

COPY . ./

RUN make build-java-version

FROM debian:buster-slim

RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /fn/bin/java-version /fn/java-version

CMD ["/fn/java-version"]